version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        versions: ["3001.0001.0000-dev-harmony-fb"]
      - dependency-name: "esprima-fb"
        versions: ["~3001.0001.0000-dev-harmony-fb"]